### ISSUE TITLE
run_nlp.sh fails

### ISSUE THREAD

**Issue by sgarnell** [FlyBrainLab/FlyBrainLab#15]
I seem to have a problem getting the nlp server to boot up. Every time I try I get the following error:

ffbo@7dd5e44ff75c:~/ffbo/bin$ ./run_nlp.sh -a hemibrain
2024-03-13 18:47:12.543757: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/home/ffbo/ffbo/ffbo.nlp_component/nlp_component/nlp_component.py", line 23, in <module>
    from neuroarch_nlp.interface import Translator
  File "/home/ffbo/miniconda/envs/ffbo/lib/python3.9/site-packages/neuroarch_nlp/interface.py", line 7, in <module>
    import quepy
  File "/home/ffbo/miniconda/envs/ffbo/lib/python3.9/site-packages/quepy/__init__.py", line 17, in <module>
    from quepy.quepyapp import install, QuepyApp
  File "/home/ffbo/miniconda/envs/ffbo/lib/python3.9/site-packages/quepy/quepyapp.py", line 21, in <module>
    from quepy.tagger import get_tagger, TaggingError
  File "/home/ffbo/miniconda/envs/ffbo/lib/python3.9/site-packages/quepy/tagger.py", line 13, in <module>
    import spacy
  File "/home/ffbo/miniconda/envs/ffbo/lib/python3.9/site-packages/spacy/__init__.py", line 14, in <module>
    from .cli.info import info  # noqa: F401
  File "/home/ffbo/miniconda/envs/ffbo/lib/python3.9/site-packages/spacy/cli/__init__.py", line 3, in <module>
    from ._util import app, setup_cli  # noqa: F401
  File "/home/ffbo/miniconda/envs/ffbo/lib/python3.9/site-packages/spacy/cli/_util.py", line 8, in <module>
    import typer
  File "/home/ffbo/miniconda/envs/ffbo/lib/python3.9/site-packages/typer/__init__.py", line 12, in <module>
    from click.termui import get_terminal_size as get_terminal_size
ImportError: cannot import name 'get_terminal_size' from 'click.termui' (/home/ffbo/miniconda/envs/ffbo/lib/python3.9/site-packages/click/termui.py)
ffbo@7dd5e44ff75c:~/ffbo/bin$

i have tried upgrading/downgrading click, typer and cloup but no combination seems to work. Can anyone help?

**Comment by yiyin** [comment]
Did you install it using the full installation script or are you using the Docker image?

**Comment by sgarnell** [comment]
Hi Yiyin, It's the docker version. But I would suggest you let me look closer at it before doing much. I think I broke my instance by a strange combination of Manim, Cairo, pycairo and a few other packages that I can't remember. Basically, I wanted to use Manim graphs with FBL but I think it's not compatible. It would be better to make another container and export the DOT files for uploading in Manim. The code base of both overlap too much and I can't tell why click and spacy die. FYI, I made a fresh instance of FBL in docker and everything works fine as expected. I will spend more time and compare the two just for leaning and report my findings here. This will help other poor soles in the future who wish to avoid all this pain :)
